on:
  push:
    branches:
      - mainsw
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server}} # Hostname only
        username: ${{ secrets.ftp_username}}
        password: ${{ secrets.ftp_password }}
        port: 21 # Specify the port separately
        # server-dir: /staging/ # Remote directory to deploy files to
